# Generated by Django 4.2.1 on 2023-06-07 19:33

from django.db import migrations, models
import voomsdb.utils.strings


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="slug",
            field=models.SlugField(default=voomsdb.utils.strings.generate_ref_no),
        ),
    ]
