# Generated by Django 4.2.1 on 2023-06-07 21:24

from django.db import migrations, models
import voomsdb.utils.strings


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_student_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="slug",
            field=models.SlugField(
                blank=True, default=voomsdb.utils.strings.generate_ref_no, null=True
            ),
        ),
    ]
