# Generated by Django 3.2.10 on 2023-06-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(max_length=30),
        ),
    ]
