# Generated by Django 3.2.10 on 2023-07-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_auto_20230727_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme.college'),
        ),
    ]
